<?php

function poll_menu(){
    $items = array();
    $items['poll_page'] = array(
        'title' => 'Ice Cream Poll',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('poll_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['poll'] = array(
        'title' => 'YOUR POLL',
        'page callback' => 'poll_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function poll_form(){
    $form['ice_cream'] = array(
        '#title' => 'Ice Cream',
        '#type' => 'textfield',
        '#description' => t('Please enter your favorite ice cream flavor.'),
        '#element_validate' => array('element_validate_string'),
        '#required' => TRUE,
    );

    $form['state_origin'] = array(
        '#title' => 'State',
        '#type' => 'textfield',
        '#description' => t('Please enter your home state.'),
        '#element_validate' => array('element_validate_state'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Ice Cream Poll',
    );


    return $form;

}

function poll_form_submit($form, &$form_state){
    $ice_cream = $form_state['values']['ice_cream'];
    $state = $form_state['values']['state_origin'];

    if(strlen($state) > 2){
        $state_array = str_split($state);
        $state_array[0] = strtoupper($state_array[0]);
        $state = implode('', $state_array);
    } else {
        $state = strtoupper($state);
    }

    $_SESSION['ice_cream'] = $ice_cream;
    $_SESSION['state'] = $state;

    $form_state['redirect'] = 'poll';
}

function element_validate_string($element){

    if(preg_match("/[^a-z]/i", $element['#value'])){
        form_error($element, t('Give us a real ice cream flavor.'));
    }
}

function element_validate_state($element){
    $states_array = array(
        'AL'=>'ALABAMA',
        'AK'=>'ALASKA',
        'AS'=>'AMERICAN SAMOA',
        'AZ'=>'ARIZONA',
        'AR'=>'ARKANSAS',
        'CA'=>'CALIFORNIA',
        'CO'=>'COLORADO',
        'CT'=>'CONNECTICUT',
        'DE'=>'DELAWARE',
        'DC'=>'DISTRICT OF COLUMBIA',
        'FM'=>'FEDERATED STATES OF MICRONESIA',
        'FL'=>'FLORIDA',
        'GA'=>'GEORGIA',
        'GU'=>'GUAM GU',
        'HI'=>'HAWAII',
        'ID'=>'IDAHO',
        'IL'=>'ILLINOIS',
        'IN'=>'INDIANA',
        'IA'=>'IOWA',
        'KS'=>'KANSAS',
        'KY'=>'KENTUCKY',
        'LA'=>'LOUISIANA',
        'ME'=>'MAINE',
        'MH'=>'MARSHALL ISLANDS',
        'MD'=>'MARYLAND',
        'MA'=>'MASSACHUSETTS',
        'MI'=>'MICHIGAN',
        'MN'=>'MINNESOTA',
        'MS'=>'MISSISSIPPI',
        'MO'=>'MISSOURI',
        'MT'=>'MONTANA',
        'NE'=>'NEBRASKA',
        'NV'=>'NEVADA',
        'NH'=>'NEW HAMPSHIRE',
        'NJ'=>'NEW JERSEY',
        'NM'=>'NEW MEXICO',
        'NY'=>'NEW YORK',
        'NC'=>'NORTH CAROLINA',
        'ND'=>'NORTH DAKOTA',
        'OH'=>'OHIO',
        'OK'=>'OKLAHOMA',
        'OR'=>'OREGON',
        'PW'=>'PALAU',
        'PA'=>'PENNSYLVANIA',
        'PR'=>'PUERTO RICO',
        'RI'=>'RHODE ISLAND',
        'SC'=>'SOUTH CAROLINA',
        'SD'=>'SOUTH DAKOTA',
        'TN'=>'TENNESSEE',
        'TX'=>'TEXAS',
        'UT'=>'UTAH',
        'VT'=>'VERMONT',
        'VI'=>'VIRGIN ISLANDS',
        'VA'=>'VIRGINIA',
        'WA'=>'WASHINGTON',
        'WV'=>'WEST VIRGINIA',
        'WI'=>'WISCONSIN',
        'WY'=>'WYOMING',
    );

        if(!in_array(strtoupper($element['#value']), $states_array) && !array_key_exists(strtoupper($element['#value']), $states_array)) {
            form_error($element, t('Please enter either a state name or abbreviation.'));
        }
}

function poll_result(){
    $ice_cream = $_SESSION['ice_cream'];
    $state = $_SESSION['state'];

    return "<p> Thank you! We have you down for <strong>$ice_cream</strong> in the state of <strong>$state</strong>";
}
